spring:
  datasource:
    username: root
    url: jdbc:mysql://127.0.0.1:3305/BOARD_PROJECT
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#spring:
#  h2:
#    console:
#      enabled: true
#      path: /h2-console
#  datasource:
#    url: jdbc:h2:~/boardproject
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        #        show_sql: true
#        dialect: org.hibernate.dialect.H2Dialect
#
#        format_sql: true
#logging.level:
#  org.hibernate.SQL: debug
#  org.hibernate.type: trace

security:
  basic:
    enabled: false

#auth:
#  jwt:
#    secret-key: tmp-key-hahahahahahahahaahahahahahahaha
#    expiration-minutes: 30


