#jpa:
#  properties:
#    hibernate:
#      dialect: org.hibernate.dialect.MySQL8Dialect
#      show_sql: true
#      format_sql: true
#      use_sql_comments: true
#      hbm2ddl:
#        auto: update
#      default_batch_fetch_size: 1000

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:~/board_project
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect

        format_sql: true
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

#auth:
#  jwt:
#    secret-key: tmp-key-hahahahahahahahaahahahahahahaha
#    expiration-minutes: 30

