spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: Njh3611.
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000